import {describe,it,expect} from 'vitest';
import {playerTemperature,teamTemperature,teamRosterTemperature,thermalScore} from './score-temperature.js';
describe('GameDay score temperatures',()=>{
 it('burns only above fifteen and freezes only finished players below ten',()=>{expect(playerTemperature(15.01,'live')).toBe('hot');expect(playerTemperature(15,'final')).toBe('neutral');expect(playerTemperature(10,'final')).toBe('neutral');expect(playerTemperature(9.99,'final')).toBe('cold');expect(playerTemperature(0,'upcoming')).toBe('neutral');expect(playerTemperature(9,'live')).toBe('neutral');expect(playerTemperature(9,'unknown')).toBe('neutral')});
 it('uses exact team boundaries and avoids judging unfinished low scores',()=>{expect(teamTemperature(120.01)).toBe('hot');expect(teamTemperature(120)).toBe('steady');expect(teamTemperature(100)).toBe('steady');expect(teamTemperature(99.99,true)).toBe('cold');expect(teamTemperature(99.99,false)).toBe('neutral')});
 it('waits for all known team starters to finish before freezing a live-week team',()=>{expect(teamRosterTemperature({score:90,known:true,remaining:0})).toBe('cold');expect(teamRosterTemperature({score:90,known:true,remaining:1})).toBe('neutral');expect(teamRosterTemperature({score:90,known:false,remaining:0})).toBe('neutral');expect(teamRosterTemperature({score:90,known:false,remaining:null},true)).toBe('cold')});
 it('keeps missing or invalid points neutral and permits recorded negative final scores',()=>{for(const value of [null,undefined,NaN,Infinity,'bad']){expect(playerTemperature(value,'final')).toBe('neutral');expect(teamTemperature(value,true)).toBe('neutral')}expect(playerTemperature(-1,'final')).toBe('cold');expect(teamTemperature(0,true)).toBe('cold')});
 it('keeps actual score text intact and names decorative cues accessibly',()=>{expect(thermalScore(21.6,'hot')).toContain('21.60');expect(thermalScore(21.6,'hot')).toContain('aria-label="On fire"');expect(thermalScore(null,'cold')).toContain('data-score-temperature="neutral"');expect(thermalScore(100,'steady',{tag:'strong'})).toMatch(/^<strong/)});
});
