import {describe,it,expect} from 'vitest';
import {playerTemperature,teamTemperature,teamRosterTemperature,pastHalftime,thermalScore} from './score-temperature.js';
describe('GameDay score temperatures',()=>{
 it('uses player thresholds from the second half onward',()=>{expect(playerTemperature(15.01,'live',true)).toBe('hot');expect(playerTemperature(15,'final')).toBe('neutral');expect(playerTemperature(10,'final')).toBe('neutral');expect(playerTemperature(9.99,'final')).toBe('cold');expect(playerTemperature(0,'upcoming')).toBe('neutral');expect(playerTemperature(9,'live')).toBe('neutral');expect(playerTemperature(9,'unknown')).toBe('neutral')});
 it('uses exact team boundaries and avoids judging unfinished low scores',()=>{expect(teamTemperature(120.01,true)).toBe('hot');expect(teamTemperature(120,true)).toBe('steady');expect(teamTemperature(100,true)).toBe('steady');expect(teamTemperature(99.99,true)).toBe('cold');expect(teamTemperature(99.99,false)).toBe('neutral')});
 it('keeps final and incomplete team status honest',()=>{expect(teamRosterTemperature({score:90,known:true,remaining:0})).toBe('cold');expect(teamRosterTemperature({score:90,known:true,remaining:1})).toBe('neutral');expect(teamRosterTemperature({score:90,known:false,remaining:0})).toBe('neutral');expect(teamRosterTemperature({score:90,known:false,remaining:null},true)).toBe('cold')});
 it('starts cold and hot player effects only after halftime or final',()=>{expect(playerTemperature(8,'live',true)).toBe('cold');expect(playerTemperature(20,'live',false)).toBe('neutral');expect(playerTemperature(20,'upcoming',true)).toBe('neutral');expect(playerTemperature(20,'unknown',true)).toBe('neutral');expect(pastHalftime('live',true)).toBe(true)});
 it('waits for every starter to reach halftime, including later kickoffs',()=>{const team={score:90,known:true,remaining:2,starters:[{state:'final'},{state:'live',afterHalftime:true}]};expect(teamRosterTemperature(team)).toBe('cold');expect(teamRosterTemperature({...team,score:125})).toBe('hot');expect(teamRosterTemperature({...team,score:110})).toBe('steady');for(const pending of [{state:'live',afterHalftime:false},{state:'upcoming'},{state:'unknown'}])expect(teamRosterTemperature({...team,starters:[team.starters[0],pending]})).toBe('neutral');expect(teamRosterTemperature({...team,starters:[]})).toBe('neutral')});
 it('keeps missing or invalid points neutral and permits recorded negative final scores',()=>{for(const value of [null,undefined,NaN,Infinity,'bad']){expect(playerTemperature(value,'final')).toBe('neutral');expect(teamTemperature(value,true)).toBe('neutral')}expect(playerTemperature(-1,'final')).toBe('cold');expect(teamTemperature(0,true)).toBe('cold')});
 it('keeps actual score text intact and names decorative cues accessibly',()=>{expect(thermalScore(21.6,'hot')).toContain('21.60');expect(thermalScore(21.6,'hot')).toContain('aria-label="On fire"');expect(thermalScore(null,'cold')).toContain('data-score-temperature="neutral"');expect(thermalScore(100,'steady',{tag:'strong'})).toMatch(/^<strong/)});
});
