import {describe,it,expect} from 'vitest';
import {sharePlayers,matchupShareSpec,tradeShareSpec,keeperShareSpec,ticketShareSpec} from './share-export-model.js';
describe('Selectable share content',()=>{
 it('offers only identified individual players, removing duplicate faces and defenses',()=>{expect(sharePlayers([{id:'4984',name:'Josh Allen'},{id:'4984',name:'Josh Allen'},{id:'BUF',position:'DEF'},{id:'1',position:'DEF'},{name:'Unknown'},{player:'678',playerName:'Player'}]).map(p=>[p.id,p.name])).toEqual([['4984','Josh Allen'],['678','Player']])});
 it('retains final scores, margin and MVP in both matchup templates',()=>{const s=matchupShareSpec({season:2026,week:4,sides:[{name:'A',score:100},{name:'B',score:99.5}],winner:{name:'A'},margin:.5,mvp:{id:'4984',name:'Josh Allen',points:26}});expect(s.results.map(r=>r.value)).toEqual(['100.00','99.50']);expect(s.summary).toBe('A wins by 0.50');expect(s.sections[0].rows[0].value).toBe('26.00 pts');expect(s.players[0].id).toBe('4984')});
 it('never adds a winner or arbitrary face to tied/empty finals',()=>{const s=matchupShareSpec({season:2026,week:4,sides:[{name:'A',score:100},{name:'B',score:100}],winner:null,margin:0,mvp:null});expect(s.summary).toBe('Final · Tied');expect(s.headline).toBe('ALL\nSQUARE.');expect(s.players).toEqual([])});
 it('preserves all multi-team packages, full reasons, totals and lineup deltas',()=>{const s=tradeShareSpec({multi:true,columns:[{from:'A',to:'B',total:20,players:[{id:'1',name:'P1',value:20}]},{from:'B',to:'C',total:30,players:[]},{from:'C',to:'A',total:40,players:[]}],call:'ACCEPT',fairness:90,remarks:[{title:'Why',copy:'Full trade explanation'}],deltas:[{team:'A',delta:-1.2},{team:'B',delta:0},{team:'C',delta:2}]});expect(s.sections.slice(0,3).map(g=>g.label)).toEqual(['A → B','B → C','C → A']);expect(s.sections[3].copy).toBe('Full trade explanation');expect(s.sections[4].rows.map(r=>r.value)).toEqual(['-1.2 / wk','0.0 / wk','+2.0 / wk'])});
 it('retains keeper round and real tenure metadata, including unmatched legacy entries',()=>{const s=keeperShareSpec({season:2026,total:2,submitted:1,rows:[{team:'A',keepers:[{id:'1',name:'Player',round:0,tenure:{year:2,max:3},overridden:true}]}],also:[{name:'Legacy',round:null}]});expect(s.sections[0].rows[0].value).toBe('R0');expect(s.sections[0].rows[0].detail).toContain('Year 2/3');expect(s.sections[1].label).toBe('Unmatched entries');expect(s.players).toHaveLength(1)});
 it('distinguishes refunded tickets and retains every settled pick',()=>{const s=ticketShareSpec({title:'Entry',who:'Member',pulled:true,status:'void',stake:50,ret:0,odds:'+140',picks:[{pick:'A',market:'vs B',odds:'+140',status:'void'}]});expect(s.status).toBe('Pulled');expect(s.results[1].label).toBe('Refunded');expect(s.results[2].value).toBe('—');expect(s.sections[0].rows[0].detail).toBe('vs B · void')});
});
