import {describe,it,expect} from 'vitest';
import {shareLayoutView,shareImageDescription,shareExportFilename} from './share-layout-model.js';
import {tradeShareSpec,ticketShareSpec,aftermathShareSpec,profileShareSpec,clubhouseShareSpec} from './share-export-model.js';

const players=Array.from({length:7},(_,i)=>({id:String(i+1),name:`Player ${i+1}`,meta:'WR · BUF',value:10+i}));
const deal={call:'ACCEPT',callTone:'accept',fairness:88,columns:[{from:'A',to:'B',players,total:91},{from:'B',to:'A',players:players.slice(0,2),total:21}],deltas:[{team:'A',delta:1.2},{team:'B',delta:-1.2}],remarks:[{title:'Keep the starter',copy:'A full explanation.'},{title:'Protect depth',copy:'Every reason remains.'}]};
const ticket=status=>ticketShareSpec({title:'10-pick entry',who:'Member',status,odds:'+3100',stake:100,ret:3200,profit:3100,picks:Array.from({length:10},(_,i)=>({pick:`Pick ${i+1}`,market:`Market ${i+1}`,status:i===9?'lost':'won',odds:'+140'}))});

describe('Tailored share exports',()=>{
 it('retains confidence in highlight and full trade descriptions',()=>{const confidence={label:'Limited support',reasons:['Expert rankings are stale.']},spec=tradeShareSpec({...deal,call:'REVIEW',confidence});for(const format of ['compact','full']){const text=shareImageDescription(spec,format);expect(text).toContain('Verdict confidence: Limited support');expect(text).toContain('Expert rankings are stale.');expect(text).toContain('not a win probability');}});
 it('keeps both package totals and explicitly counts players left out of highlights',()=>{const v=shareLayoutView(tradeShareSpec(deal));expect(v.columns.map(c=>[c.players.length,c.omitted,c.total])).toEqual([[3,4,91],[2,0,21]]);expect(v.remarks).toHaveLength(1);expect(deal.columns[0].players).toHaveLength(7)});
 it('retains every player, team delta and full trade reason in the full export',()=>{const s=tradeShareSpec(deal),v=shareLayoutView(s,'full'),text=shareImageDescription(s,'full');expect(v.columns[0].players).toHaveLength(7);expect(v.columns[0].omitted).toBe(0);expect(v.remarks).toEqual(deal.remarks);expect(text).toContain('Every reason remains.');expect(text).toContain('Player 7');expect(text).toContain('-1.2 points per week')});
 it('labels all senders and recipients correctly in a three-way highlight',()=>{const s=tradeShareSpec({...deal,columns:[...deal.columns,{from:'C',to:'A',players,total:50}]});expect(shareLayoutView(s).columns.map(c=>[c.from,c.to,c.players.length,c.omitted])).toEqual([['A','B',1,6],['B','A',1,1],['C','A',1,6]])});
 it('keeps the total leg count and odds while limiting a highlight ticket',()=>{const v=shareLayoutView(ticket('open'));expect(v.picks).toHaveLength(5);expect(v.omitted).toBe(5);expect(v.ticket.picks).toHaveLength(10);expect(v.ticket.odds).toBe('+3100');expect(shareImageDescription(ticket('open'))).toContain('All picks must land')});
 it('keeps all graded legs in a full ticket, including the losing final pick',()=>{const v=shareLayoutView(ticket('lost'),'full');expect(v.picks).toHaveLength(10);expect(v.picks[9].status).toBe('lost');expect(v.returnValue).toBe(0);expect(v.status).toBe('Torn up');expect(v.omitted).toBe(0)});
 it.each([['won','Paid',3200],['lost','Returned',0],['void','Void','—'],['open','To return',3200]])('preserves %s settlement semantics', (status,label,value)=>{const v=shareLayoutView(ticket(status));expect(v.returnLabel).toBe(label);expect(v.returnValue).toBe(value)});
 it('distinguishes a pulled ticket from a house void and shows the actual refunded stake',()=>{const s=ticket('void');s.ticket.pulled=true;const v=shareLayoutView(s);expect(v.status).toBe('Pulled');expect(v.returnLabel).toBe('Refunded');expect(v.returnValue).toBe(100)});
 it('keeps all weekly stories, player podiums and matchup scores in full details',()=>{const s=aftermathShareSpec({season:2026,week:4,title:'Week 4',king:{name:'A',value:145.8},story:'The full weekly story.',highlights:Array.from({length:5},(_,i)=>({label:`Award ${i}`,title:`Team ${i}`,detail:`Fact ${i}`})),players:{starters:[{id:'4984',name:'Josh Allen',points:32.6}],bench:[{id:'4046',name:'Patrick Mahomes',points:25}]},games:[{winner:{name:'A',value:145.8},loser:{name:'B',value:119.4},margin:26.4}]});const v=shareLayoutView(s);expect(v.highlights).toHaveLength(3);expect(v.omitted).toBe(1);expect(v.sections).toEqual([]);expect(v.recap.mvp.name).toBe('Josh Allen');const full=shareImageDescription(s,'full');expect(full).toContain('Fact 4');expect(full).toContain('The full weekly story.');expect(full).toContain('Patrick Mahomes');expect(full).toContain('145.80 – 119.40')});
 it('does not invent a single weekly winner or turn unavailable scores into zero',()=>{const s=clubhouseShareSpec({season:2026,week:4,awards:[{key:'high-score',label:'Final boss',winners:[{name:'A',score:100},{name:'B',score:100}],detail:'100 points'}],games:[{left:{name:'A',score:null},right:{name:'B',score:0}}]});expect(s.recap.hero.name).toBe('A & B');expect(s.detailSections[0].rows[0].value).toBe('— – 0.00');expect(s.players).toEqual([])});
 it('keeps the complete profile available while counting unshown career receipts',()=>{const d={who:'Member',team:'Team',record:'20-10',winPct:2/3,points:'3,000',avgFinish:'4.5',seasons:3,trophyCase:[['Title','2023'],['Runner-up','2024'],['Win streak','6']],crimeScene:[['Basement','12th'],['Low week','49'],['Loss streak','5']],verdict:'A factual verdict.'};const s=profileShareSpec(d);expect(shareLayoutView(s).omitted).toBe(2);expect(shareLayoutView(s,'full').trophies).toEqual(d.trophyCase);expect(shareImageDescription(s,'full')).toContain('Loss streak, 5');expect(shareImageDescription(s,'full')).toContain('67%')});
 it('gives different downloads distinct, readable names',()=>{expect(shareExportFilename('dfl-deal.png','compact','clean')).toBe('dfl-deal-highlights.png');expect(shareExportFilename('dfl-deal.png','full','photo')).toBe('dfl-deal-full-photo.png')});
});
