-- =====================================================================
-- broadcast_items - the slides a human puts on the front page by hand.
-- ---------------------------------------------------------------------
-- Run this once in the Supabase SQL editor.
--
-- SECURITY REVIEW (required for every new table in this app):
--
--   READ   public. This is the front page of DFL HQ - anonymous visitors
--          and every member see it. That is the whole point of the table,
--          so there is nothing here that is not already meant to be on a
--          billboard. NOTHING PRIVATE GOES IN THIS TABLE: no dues, no
--          member contact details, no admin notes. It is a public sign.
--
--   WRITE  admins only, enforced by is_admin() in the policy itself -
--          the same bcrypt check on the x-admin-token header that every
--          other admin write in this app already uses. Hiding the panel
--          in the UI is not the control; this is.
--
--   The anon key can therefore SELECT and nothing else. That is checked
--   at the bottom of this file rather than assumed.
--
-- WHY A TABLE AND NOT A SETTING: app_settings holds one JSON blob, which
-- means two admins editing at once silently overwrite each other and no
-- row can be scheduled independently. These are rows.
-- =====================================================================

create table if not exists public.broadcast_items (
  id          bigint generated by default as identity primary key,

  -- What it looks like. Mirrors the item shape broadcast-deck.js produces,
  -- so a hand-written slide and a generated one are the same object by the
  -- time broadcast-stage.js draws it.
  treatment   text    not null default 'announcement'
                check (treatment in ('scoreboard','champion','stat','announcement','event','hero')),
  kicker      text    not null default '',
  headline    text    not null default '',
  subtitle    text    not null default '',
  body        text    not null default '',
  figure      text    not null default '',
  image       text,
  href        text,

  -- TEMPORAL HONESTY. A hand-written slide has to answer "when is this?"
  -- exactly like a generated one does. 'none' is allowed and means the
  -- slide makes no claim about time at all (an identity or a house ad).
  temporal    text    not null default 'none'
                check (temporal in ('live','upcoming','recent','final','historical','none')),

  -- Where it sits. weight is added to the manual priority band, so an
  -- admin can push a slide above or below the automatic ones without
  -- editing code. featured pins it to the very top for as long as it is
  -- scheduled.
  weight      int     not null default 0,
  featured    boolean not null default false,

  -- Scheduling. Both null means "always". Checked in the browser against
  -- the reader's own clock, so these are timestamptz and never dates.
  starts_at   timestamptz,
  ends_at     timestamptz,

  active      boolean not null default true,
  created_at  timestamptz not null default now(),

  -- An end before its start is always a mistake, and one that would make
  -- the slide silently never appear.
  constraint broadcast_items_window check (ends_at is null or starts_at is null or ends_at > starts_at)
);

-- The front page asks for "active slides in their window, best first", and
-- it asks on every load.
create index if not exists broadcast_items_live_idx
  on public.broadcast_items (active, featured desc, weight desc, created_at desc);

alter table public.broadcast_items enable row level security;

-- Rebuilt by name rather than "if not exists", so re-running this file
-- leaves exactly these four policies and no forgotten older one. This is
-- the same lesson golf_scores taught: a stale permissive policy from an
-- earlier design is invisible until you enumerate them.
drop policy if exists "broadcast read"   on public.broadcast_items;
drop policy if exists "broadcast insert" on public.broadcast_items;
drop policy if exists "broadcast update" on public.broadcast_items;
drop policy if exists "broadcast delete" on public.broadcast_items;

create policy "broadcast read"   on public.broadcast_items for select using (true);
create policy "broadcast insert" on public.broadcast_items for insert with check (is_admin());
create policy "broadcast update" on public.broadcast_items for update using (is_admin()) with check (is_admin());
create policy "broadcast delete" on public.broadcast_items for delete using (is_admin());

-- ---------------------------------------------------------------------
-- Prove it, rather than trust it. Run this block as the anon role and
-- every write must be refused.
--
--   set local role anon;
--   insert into public.broadcast_items (headline) values ('should fail');
--   -- expected: new row violates row-level security policy
--   select count(*) from public.broadcast_items;  -- allowed
--   reset role;
-- ---------------------------------------------------------------------
