-- =====================================================================
-- DFL HQ - commissioner-authored breaking alerts
-- Run after members_schema.sql, commissioner_roles_schema.sql and
-- notifications_schema.sql. Safe to re-run.
-- =====================================================================

create table if not exists public.custom_breaking_alerts (
  id bigint generated by default as identity primary key,
  label text not null default 'BREAKING' check (char_length(trim(label)) between 1 and 28),
  title text not null check (char_length(trim(title)) between 1 and 120),
  message text not null default '' check (char_length(message) <= 240),
  target_url text not null default '#/home' check (target_url ~ '^#/[a-z0-9?=&_/%.-]*$'),
  active boolean not null default true,
  created_by bigint references public.members(id) on delete set null,
  notification_message_id bigint unique references public.notification_messages(id) on delete set null,
  notified_at timestamptz,
  ended_at timestamptz,
  ended_by bigint references public.members(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists custom_breaking_alerts_active_idx
  on public.custom_breaking_alerts(active, created_at desc) where active;

alter table public.custom_breaking_alerts enable row level security;
revoke all on table public.custom_breaking_alerts from anon, authenticated;
grant select, insert on table public.custom_breaking_alerts to anon, authenticated;
grant update(active, notification_message_id, notified_at, ended_at, ended_by)
  on table public.custom_breaking_alerts to anon, authenticated;
grant usage, select on sequence public.custom_breaking_alerts_id_seq to anon, authenticated;

drop policy if exists "public read" on public.custom_breaking_alerts;
create policy "public read" on public.custom_breaking_alerts for select
  to anon, authenticated using (true);

drop policy if exists "commissioner create" on public.custom_breaking_alerts;
create policy "commissioner create" on public.custom_breaking_alerts for insert
  to anon, authenticated
  with check (public.has_commissioner_permission('sleeper'));

drop policy if exists "commissioner update" on public.custom_breaking_alerts;
create policy "commissioner update" on public.custom_breaking_alerts for update
  to anon, authenticated
  using (public.has_commissioner_permission('sleeper'))
  with check (public.has_commissioner_permission('sleeper'));

create or replace function public.end_custom_breaking_alert(alert_id bigint)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare affected integer;
begin
  if not public.has_commissioner_permission('sleeper') then
    raise exception 'Commissioner Sleeper permission required';
  end if;
  update public.custom_breaking_alerts
     set active = false,
         ended_at = now(),
         ended_by = nullif(
           nullif(current_setting('request.headers', true), '')::json ->> 'x-member-id', ''
         )::bigint
   where id = alert_id and active;
  get diagnostics affected = row_count;
  return affected > 0;
end;
$$;

revoke all on function public.end_custom_breaking_alert(bigint) from public;
grant execute on function public.end_custom_breaking_alert(bigint) to anon, authenticated;

