-- Additive clubhouse conversations and public league search.
-- Wall alerts contain only public post/reply text. Other targeted alerts retain
-- their enrolled-device authentication; no push keys or private data are exposed.
create schema if not exists private;
create table public.member_wall_replies (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.member_wall_posts(id) on delete cascade,
  member_id bigint not null references public.members(id),
  body text not null check (char_length(btrim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);
create index member_wall_replies_post_created_idx on public.member_wall_replies(post_id,created_at,id);
create index member_wall_replies_member_idx on public.member_wall_replies(member_id);
alter table public.member_wall_replies enable row level security;
create policy "read public replies" on public.member_wall_replies for select using (true);
create policy "write own replies" on public.member_wall_replies for insert with check(member_id=(select public.dfl_current_member()));
create policy "delete own or moderated replies" on public.member_wall_replies for delete using(member_id=(select public.dfl_current_member()) or (select public.is_admin()) or (select public.is_commissioner()));
grant select,insert,delete on public.member_wall_replies to anon,authenticated;
grant usage,select on sequence public.member_wall_replies_id_seq to anon,authenticated;
create view public.member_wall_reply_counts with (security_invoker=true) as
select post_id,count(*)::integer reply_count from public.member_wall_replies group by post_id;
grant select on public.member_wall_reply_counts to anon,authenticated;

create function private.wall_conversation_notice() returns trigger
language plpgsql security definer set search_path='' as $$
declare targets bigint[]; owner_id bigint; post_id bigint; author text;
begin
  if tg_table_name='member_wall_replies' then
    post_id:=new.post_id;
    select member_id into owner_id from public.member_wall_posts where id=post_id;
  else post_id:=new.id; end if;
  select display_name into author from public.members where id=new.member_id;
  select array_agg(distinct m.id) into targets from public.members m
    where m.id<>new.member_id and
      (m.id=owner_id or position(lower('@{'||m.display_name||'}') in lower(new.body))>0);
  if cardinality(targets)>0 then
    insert into public.notification_messages(title,body,category,target_url,audience,target_member_ids,sent_by_member_id,source_key)
    values(left(coalesce(author,'Member')||case when owner_id is not null then ' replied on the Wall' else ' mentioned you on the Wall' end,80),
      left(new.body,240),'announcements','#/wall?post='||post_id,'members',targets,new.member_id,
      'wall:'||case when owner_id is not null then 'reply:' else 'post:' end||new.id);
  end if;
  return new;
end;
$$;
revoke all on function private.wall_conversation_notice() from public,anon,authenticated;
create trigger wall_post_mentions after insert on public.member_wall_posts for each row execute function private.wall_conversation_notice();
create trigger wall_reply_mentions after insert on public.member_wall_replies for each row execute function private.wall_conversation_notice();

create or replace function public.league_search(search_text text)
returns table(kind text,id text,title text,detail text,url text)
language sql stable security invoker set search_path='' as $$
  with q as (select lower(left(btrim(search_text),80)) text),
  results as (
    (select 'Members'::text kind,m.id::text id,m.display_name title,coalesce(m.team_name,'') detail,'#/profile?id='||m.id url
      from public.members m,q where length(q.text)>=2 and position(q.text in lower(m.display_name||' '||coalesce(m.team_name,'')))>0 order by m.display_name limit 12)
    union all
    (select 'Records',h.id::text,h.year||' · '||h.category,concat_ws(' · ',h.winner,h.notes),'#/history?entry='||h.id
      from public.history h,q where length(q.text)>=2 and position(q.text in lower(concat_ws(' ',h.year,h.category,h.winner,h.notes)))>0 order by h.year desc,h.id desc limit 12)
    union all
    (select 'Wall posts',p.id::text,coalesce(m.display_name,'Member')||' · '||to_char(p.created_at,'Mon DD, YYYY'),left(p.body,160),'#/wall?post='||p.id
      from public.member_wall_posts p left join public.members m on m.id=p.member_id,q
      where length(q.text)>=2 and position(q.text in lower(p.body))>0 order by p.created_at desc,p.id desc limit 12)
  ) select * from results;
$$;
revoke all on function public.league_search(text) from public;
grant execute on function public.league_search(text) to anon,authenticated;

create or replace function public.notification_inbox(max_rows integer default 50)
returns table(id bigint,title text,body text,category text,target_url text,created_at timestamptz,is_read boolean)
language sql stable security definer set search_path='' as $$
 select n.id,n.title,n.body,n.category,n.target_url,n.created_at,
   exists(select 1 from public.notification_reads r where r.message_id=n.id and r.member_id=case when n.source_key ~ '^wall:(post|reply):[0-9]+$' then public.notification_member_id() else public.notification_authenticated_member_id() end)
 from public.notification_messages n
 where public.notification_member_id() is not null
   and (n.audience='all' or public.notification_authenticated_member_id()=any(n.target_member_ids)
        or (n.source_key ~ '^wall:(post|reply):[0-9]+$' and public.notification_member_id()=any(n.target_member_ids)))
   and not exists(select 1 from public.notification_dismissals d where d.message_id=n.id and d.member_id=public.notification_member_id())
 order by n.created_at desc,n.id desc limit least(greatest(coalesce(max_rows,50),1),100);
$$;
create or replace function public.notification_unread_count() returns integer
language sql stable security definer set search_path='' as $$
 select count(*)::integer from public.notification_messages n
 where ((public.notification_authenticated_member_id() is not null and (n.audience='all' or public.notification_authenticated_member_id()=any(n.target_member_ids)))
        or (n.source_key ~ '^wall:(post|reply):[0-9]+$' and public.notification_member_id()=any(n.target_member_ids)))
 and not exists(select 1 from public.notification_reads r where r.message_id=n.id and r.member_id=case when n.source_key ~ '^wall:(post|reply):[0-9]+$' then public.notification_member_id() else public.notification_authenticated_member_id() end)
 and not exists(select 1 from public.notification_dismissals d where d.message_id=n.id and d.member_id=public.notification_member_id());
$$;
create or replace function public.mark_notifications_read(message_ids bigint[]) returns integer
language plpgsql security definer set search_path='' as $$
declare mid bigint:=public.notification_member_id(); authenticated_mid bigint:=public.notification_authenticated_member_id(); affected integer;
begin
 if mid is null then raise exception 'Pick your DFL member first'; end if;
 insert into public.notification_reads(message_id,member_id)
 select n.id,mid from public.notification_messages n where n.id=any(coalesce(message_ids,'{}'))
 and ((authenticated_mid is not null and (n.audience='all' or authenticated_mid=any(n.target_member_ids)))
      or (n.source_key ~ '^wall:(post|reply):[0-9]+$' and mid=any(n.target_member_ids)))
 on conflict(message_id,member_id) do update set read_at=now();
 get diagnostics affected=row_count;return affected;
end;
$$;
