-- =====================================================================
-- DFL HQ - member notification inbox and per-device Web Push
-- Run once in the Supabase SQL Editor. Safe to re-run.
-- =====================================================================

create table if not exists public.notification_messages (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 80),
  body text not null check (char_length(body) between 1 and 240),
  category text not null default 'announcements'
    check (category in ('announcements','trades','polls','fees','matchups','events','updates')),
  target_url text not null default '#/home' check (target_url ~ '^#/'),
  audience text not null default 'all' check (audience in ('all','members')),
  target_member_ids bigint[] not null default '{}',
  sent_by_member_id bigint references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint notification_target_members_required
    check (audience = 'all' or cardinality(target_member_ids) > 0)
);

create index if not exists notification_messages_created_idx
  on public.notification_messages(created_at desc);
create index if not exists notification_messages_targets_idx
  on public.notification_messages using gin(target_member_ids);

create table if not exists public.notification_reads (
  message_id bigint not null references public.notification_messages(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key(message_id, member_id)
);

/*
  DELETING A LEAGUE NOTICE ONLY DELETES YOUR COPY.

  notification_messages holds ONE row per announcement for the whole league, so
  a real delete would clear it off twelve phones. A dismissal is per member,
  exactly like a read mark, and the message itself is untouched.

  Keyed on notification_member_id() rather than the authenticated id that
  notification_reads uses. Read state only ever exists for a device that
  enrolled for push, but the inbox is shown to every member whether or not they
  turned notifications on - gating delete on a push device token would leave
  most of the league unable to clear their own list.
*/
create table if not exists public.notification_dismissals (
  message_id bigint not null references public.notification_messages(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  dismissed_at timestamptz not null default now(),
  primary key(message_id, member_id)
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  device_token_hash bytea,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  categories jsonb not null default
    '["announcements","trades","polls","fees","matchups","events"]'::jsonb,
  device_label text,
  user_agent text,
  enabled boolean not null default true,
  failure_count integer not null default 0,
  last_success_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint push_categories_array check (jsonb_typeof(categories) = 'array')
);

/* App updates stay available as an opt-in category. Existing devices that
   still have the original untouched all-categories default move to the quieter
   default; customized category lists are preserved exactly as chosen. */
alter table public.push_subscriptions alter column categories set default
  '["announcements","trades","polls","fees","matchups","events"]'::jsonb;
update public.push_subscriptions
   set categories = categories - 'updates', updated_at = now()
 where categories = '["announcements","trades","polls","fees","matchups","events","updates"]'::jsonb;

-- The Web Push signing key is created by the Edge Function on first use. It is
-- never returned by an RPC, never granted to browser roles, and never enters
-- source control. Only the server-secret client can read this row.
create table if not exists public.notification_push_config (
  singleton boolean primary key default true check (singleton = true),
  public_key text not null,
  private_key text not null,
  created_at timestamptz not null default now()
);

-- Upgrade-safe if an earlier notification prototype created this table before
-- device tokens existed. Legacy rows remain harmless: they cannot satisfy the
-- authenticated-device lookup until the member re-enrols with their PIN.
alter table public.push_subscriptions
  add column if not exists device_token_hash bytea;

create index if not exists push_subscriptions_member_idx
  on public.push_subscriptions(member_id) where enabled;

alter table public.notification_messages enable row level security;
alter table public.notification_reads enable row level security;
alter table public.notification_dismissals enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_push_config enable row level security;
revoke all on table public.notification_messages, public.notification_reads,
  public.notification_dismissals,
  public.push_subscriptions, public.notification_push_config from anon, authenticated;
-- No direct client policies. The browser uses the narrowly scoped RPCs below;
-- the Edge Function uses a server secret and is the only notification writer.

create or replace function public.notification_member_id()
returns bigint
language plpgsql stable
set search_path = ''
as $$
declare raw_id text;
begin
  raw_id := nullif(current_setting('request.headers', true), '')::jsonb ->> 'x-member-id';
  if raw_id is null or raw_id !~ '^[0-9]+$' then return null; end if;
  return raw_id::bigint;
exception when others then return null;
end;
$$;

create or replace function public.notification_device_token()
returns text
language sql stable
set search_path = ''
as $$
  select nullif(current_setting('request.headers', true), '')::jsonb ->> 'x-device-token';
$$;

create or replace function public.notification_authenticated_member_id()
returns bigint
language sql stable security definer
set search_path = public, extensions
as $$
  select p.member_id
    from public.push_subscriptions p
   where p.member_id = public.notification_member_id()
     and p.enabled = true
     and p.device_token_hash = extensions.digest(public.notification_device_token(), 'sha256')
   limit 1;
$$;

create or replace function public.notification_inbox(max_rows integer default 50)
returns table(
  id bigint, title text, body text, category text, target_url text,
  created_at timestamptz, is_read boolean
)
language sql stable security definer
set search_path = public
as $$
  select n.id, n.title, n.body, n.category, n.target_url, n.created_at,
         exists(select 1 from public.notification_reads r
                 where r.message_id = n.id and r.member_id = public.notification_authenticated_member_id())
    from public.notification_messages n
   where public.notification_member_id() is not null
     and (n.audience = 'all' or public.notification_authenticated_member_id() = any(n.target_member_ids))
     and not exists(select 1 from public.notification_dismissals d
                     where d.message_id = n.id and d.member_id = public.notification_member_id())
   order by n.created_at desc
   limit least(greatest(coalesce(max_rows, 50), 1), 100);
$$;

create or replace function public.notification_unread_count()
returns integer
language sql stable security definer
set search_path = public
as $$
  select count(*)::integer
    from public.notification_messages n
   where public.notification_authenticated_member_id() is not null
     and (n.audience = 'all' or public.notification_authenticated_member_id() = any(n.target_member_ids))
     and not exists(select 1 from public.notification_reads r
                     where r.message_id = n.id and r.member_id = public.notification_authenticated_member_id())
     and not exists(select 1 from public.notification_dismissals d
                     where d.message_id = n.id and d.member_id = public.notification_member_id());
$$;

create or replace function public.mark_notifications_read(message_ids bigint[])
returns integer
language plpgsql security definer
set search_path = public
as $$
declare mid bigint := public.notification_authenticated_member_id(); affected integer;
begin
  if mid is null then raise exception 'Pick your DFL member first'; end if;
  insert into public.notification_reads(message_id, member_id)
  select n.id, mid from public.notification_messages n
   where n.id = any(coalesce(message_ids, '{}'))
     and (n.audience = 'all' or mid = any(n.target_member_ids))
  on conflict (message_id, member_id) do update set read_at = now();
  get diagnostics affected = row_count;
  return affected;
end;
$$;

create or replace function public.dismiss_notifications(message_ids bigint[])
returns integer
language plpgsql security definer
set search_path = public
as $$
declare mid bigint := public.notification_member_id(); affected integer;
begin
  if mid is null then raise exception 'Pick your DFL member first'; end if;
  insert into public.notification_dismissals(message_id, member_id)
  select n.id, mid from public.notification_messages n
   where n.id = any(coalesce(message_ids, '{}'))
     and (n.audience = 'all' or mid = any(n.target_member_ids))
  on conflict (message_id, member_id) do nothing;
  get diagnostics affected = row_count;
  return affected;
end;
$$;

/* Clears whatever is in this member's inbox right now. A notice sent after
   this call is new mail, not something they already dismissed. */
create or replace function public.clear_notification_inbox()
returns integer
language plpgsql security definer
set search_path = public
as $$
declare mid bigint := public.notification_member_id(); affected integer;
begin
  if mid is null then raise exception 'Pick your DFL member first'; end if;
  insert into public.notification_dismissals(message_id, member_id)
  select n.id, mid from public.notification_messages n
   where (n.audience = 'all' or mid = any(n.target_member_ids))
  on conflict (message_id, member_id) do nothing;
  get diagnostics affected = row_count;
  return affected;
end;
$$;

/*
  ENABLING NOTIFICATIONS ASKS FOR NOTHING.

  This used to demand the member's Profile PIN, and the notifications page
  refused to enable at all until a member had set one. That was too high a
  price for turning on alerts: most of the league has no PIN, so the feature
  they were being offered was really a link to a settings page.

  The PIN is no longer required. Enrolment now trusts x-member-id the same way
  the rest of the app already does, and the device token it returns is still
  what every later call is checked against - the inbox, the unread count, the
  read marks and the per-device categories are all unchanged.

  WHAT THIS GIVES UP, PLAINLY. x-member-id is chosen by the browser and proves
  nothing. Anyone who can reach this API can now enrol a device under another
  member's id, receive that member's pushes and read their inbox. For a league
  inbox holding announcements, trades, polls and fee reminders that is an
  accepted trade, not an oversight. Do not extend this token to anything that
  would matter more.
*/
drop function if exists public.enroll_push_subscription(text,text,text,text,jsonb,text,text);

create or replace function public.enroll_push_subscription(
  push_endpoint text, push_p256dh text, push_auth text,
  push_categories jsonb, push_device_label text default null,
  push_user_agent text default null
)
returns text
language plpgsql security definer
set search_path = public
as $$
declare
  mid bigint := public.notification_member_id();
  raw_token text;
begin
  if mid is null then raise exception 'Pick your DFL member first'; end if;
  if push_endpoint is null or push_endpoint !~ '^https://' then raise exception 'Invalid push endpoint'; end if;
  if coalesce(push_p256dh, '') = '' or coalesce(push_auth, '') = '' then raise exception 'Invalid push keys'; end if;
  if jsonb_typeof(coalesce(push_categories, '[]'::jsonb)) <> 'array' then raise exception 'Categories must be an array'; end if;

  raw_token := encode(extensions.gen_random_bytes(32), 'base64');
  insert into public.push_subscriptions(
    member_id, device_token_hash, endpoint, p256dh, auth, categories, device_label, user_agent, enabled, failure_count, updated_at
  ) values (
    mid, extensions.digest(raw_token, 'sha256'), push_endpoint, push_p256dh, push_auth, coalesce(push_categories, '[]'::jsonb),
    nullif(left(coalesce(push_device_label, ''), 80), ''),
    nullif(left(coalesce(push_user_agent, ''), 300), ''), true, 0, now()
  )
  on conflict(endpoint) do update set
    member_id = excluded.member_id, device_token_hash = excluded.device_token_hash,
    p256dh = excluded.p256dh, auth = excluded.auth,
    categories = excluded.categories, device_label = excluded.device_label,
    user_agent = excluded.user_agent, enabled = true, failure_count = 0, updated_at = now();
  return raw_token;
end;
$$;

create or replace function public.save_push_preferences(push_endpoint text, push_categories jsonb)
returns boolean
language plpgsql security definer
set search_path = public, extensions
as $$
declare mid bigint := public.notification_authenticated_member_id();
begin
  if mid is null then raise exception 'Unlock notification settings again'; end if;
  if jsonb_typeof(coalesce(push_categories, '[]'::jsonb)) <> 'array' then raise exception 'Categories must be an array'; end if;
  update public.push_subscriptions set categories = push_categories, updated_at = now()
   where endpoint = push_endpoint and member_id = mid;
  return found;
end;
$$;

create or replace function public.my_push_preferences(push_endpoint text)
returns table(enabled boolean, categories jsonb, device_label text)
language sql stable security definer
set search_path = public
as $$
  select p.enabled, p.categories, p.device_label
    from public.push_subscriptions p
   where p.endpoint = push_endpoint and p.member_id = public.notification_authenticated_member_id();
$$;

create or replace function public.disable_push_subscription(push_endpoint text)
returns boolean
language plpgsql security definer
set search_path = public
as $$
begin
  update public.push_subscriptions set enabled = false, updated_at = now()
   where endpoint = push_endpoint and member_id = public.notification_authenticated_member_id();
  return found;
end;
$$;

revoke all on function public.notification_member_id() from public;
revoke all on function public.notification_device_token() from public;
revoke all on function public.notification_authenticated_member_id() from public;

revoke all on function public.notification_inbox(integer) from public;
revoke all on function public.notification_unread_count() from public;
revoke all on function public.mark_notifications_read(bigint[]) from public;
revoke all on function public.dismiss_notifications(bigint[]) from public;
revoke all on function public.clear_notification_inbox() from public;
revoke all on function public.enroll_push_subscription(text,text,text,jsonb,text,text) from public;
revoke all on function public.save_push_preferences(text,jsonb) from public;
revoke all on function public.my_push_preferences(text) from public;
revoke all on function public.disable_push_subscription(text) from public;

grant execute on function public.notification_inbox(integer) to anon, authenticated;
grant execute on function public.notification_unread_count() to anon, authenticated;
grant execute on function public.mark_notifications_read(bigint[]) to anon, authenticated;
grant execute on function public.dismiss_notifications(bigint[]) to anon, authenticated;
grant execute on function public.clear_notification_inbox() to anon, authenticated;
grant execute on function public.enroll_push_subscription(text,text,text,jsonb,text,text) to anon, authenticated;
grant execute on function public.save_push_preferences(text,jsonb) to anon, authenticated;
grant execute on function public.my_push_preferences(text) to anon, authenticated;
grant execute on function public.disable_push_subscription(text) to anon, authenticated;
