-- =====================================================================
-- DFL presence - an aggregate "somebody else is here" counter.
-- ---------------------------------------------------------------------
-- Run this once in the Supabase SQL editor. One table, one function.
--
-- THIS TABLE CONTAINS NO IDENTITY, DELIBERATELY.
--
-- DFL HQ has no per-user authentication: a member is whichever id is in
-- this device's localStorage, which a client can set to anything. So a
-- row here is keyed by a RANDOM PER-BROWSER TOKEN and nothing else. No
-- member id, no name, no IP, no user agent, no route history.
--
-- That is not laziness, it is the only honest option. Storing member_id
-- would let the app say "Kirk is online" on the strength of a claim any
-- client could forge - a statement about a real person that the auth
-- model cannot support. Named presence waits for Supabase Auth and
-- auth.uid(). Until then the app can only say HOW MANY, never WHO.
--
-- SECURITY:
--   The table is NOT readable, not even anonymously - there is no select
--   policy, so RLS denies every read. The only way to learn anything is
--   dfl_presence(), a security definer function that returns COUNTS.
--   Even if the token were somehow meaningful, nobody can enumerate it.
--
--   Writes go through the same function. There is no insert or update
--   policy either, so a client cannot write arbitrary rows directly.
--
-- WHAT THIS IS NOT: an activity log. Rows are upserted in place, one per
-- browser, and anything older than ten minutes is deleted on every call.
-- The table's size is bounded by how many people are actually using the
-- app, and it keeps no history of where anybody went.
-- =====================================================================

create table if not exists public.presence (
  -- A random token generated by the browser. Not a member, not a person.
  token   uuid primary key,
  -- Which part of the app, so the counter can say "in the Arena". A
  -- coarse bucket, never a full route or a page history.
  zone    text not null default 'hq' check (zone in ('hq','arena','golf')),
  seen_at timestamptz not null default now()
);

create index if not exists presence_seen_idx on public.presence (seen_at);

alter table public.presence enable row level security;

-- No policies at all: RLS denies select, insert, update and delete to
-- every client. Everything goes through the function below.
drop policy if exists "presence read"  on public.presence;
drop policy if exists "presence write" on public.presence;

/*
  THE ONLY DOOR IN.

  security definer, so it runs as the owner and can touch a table nobody
  else can. It does three things and returns only numbers:

    1. deletes anything stale (this is the whole retention policy)
    2. upserts the caller's own row
    3. counts what is left, in total and in the Arena

  A caller can therefore: say "I am here", and learn how many others are.
  It cannot read a single row, learn a token, or find out who anybody is.

  The token is supplied by the client, which means somebody determined
  could loop with fresh tokens and inflate the number. That is accepted:
  the worst case is a fun counter reading high, and the alternative is an
  identity system this app does not have. It is not a security control,
  it is a lava lamp.
*/
create or replace function public.dfl_presence(p_token uuid, p_zone text default 'hq')
returns table (active int, arena int)
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Retention: ten minutes. Nothing here is history.
  delete from public.presence where seen_at < now() - interval '10 minutes';

  if p_token is not null then
    insert into public.presence (token, zone, seen_at)
    values (p_token, coalesce(nullif(p_zone, ''), 'hq'), now())
    on conflict (token) do update
      set zone = excluded.zone, seen_at = now();
  end if;

  -- "Active" is a two minute window, so a closed tab drops off quickly
  -- rather than haunting the counter for the full retention period.
  return query
    select
      count(*)::int,
      count(*) filter (where zone = 'arena')::int
    from public.presence
    where seen_at > now() - interval '2 minutes';
end;
$$;

revoke all on function public.dfl_presence(uuid, text) from public;
grant execute on function public.dfl_presence(uuid, text) to anon, authenticated;

-- ---------------------------------------------------------------------
--   set local role anon;
--   select * from public.presence;            -- expected: permission denied
--   select * from public.dfl_presence(gen_random_uuid(), 'hq');  -- allowed
--   reset role;
-- ---------------------------------------------------------------------
