-- DFL HQ Rule Proposals
-- Members may submit proposals and cast one Yes/No vote each.
-- Commissioners/admins control proposal status. Safe to re-run.

create table if not exists public.rule_proposals (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 3 and 100),
  body text not null check (char_length(trim(body)) between 3 and 1200),
  status text not null default 'open' check (status in ('open','passed','rejected','adopted','withdrawn')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rule_proposal_votes (
  proposal_id bigint not null references public.rule_proposals(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  vote text not null check (vote in ('yes','no')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (proposal_id,member_id)
);

alter table public.rule_proposals enable row level security;
alter table public.rule_proposal_votes enable row level security;

drop policy if exists "proposals readable" on public.rule_proposals;
create policy "proposals readable" on public.rule_proposals for select using (true);
drop policy if exists "proposal votes readable" on public.rule_proposal_votes;
create policy "proposal votes readable" on public.rule_proposal_votes for select using (true);

create or replace function public.proposal_current_member_id()
returns bigint language sql stable as $$
  select nullif(current_setting('request.headers',true)::jsonb->>'x-member-id','')::bigint;
$$;

create or replace function public.proposal_submit(p_title text,p_body text)
returns bigint language plpgsql security definer set search_path=public as $$
declare mid bigint:=public.proposal_current_member_id(); new_id bigint;
begin
  if mid is null then raise exception 'Select your DFL member first'; end if;
  if char_length(trim(coalesce(p_title,''))) < 3 then raise exception 'Give the proposal a title'; end if;
  if char_length(trim(coalesce(p_body,''))) < 3 then raise exception 'Explain the rule change'; end if;
  insert into public.rule_proposals(member_id,title,body)
  values(mid,left(trim(p_title),100),left(trim(p_body),1200)) returning id into new_id;
  return new_id;
end; $$;

grant execute on function public.proposal_submit(text,text) to anon,authenticated;

create or replace function public.proposal_vote(p_proposal_id bigint,p_vote text)
returns void language plpgsql security definer set search_path=public as $$
declare mid bigint:=public.proposal_current_member_id(); st text;
begin
  if mid is null then raise exception 'Select your DFL member first'; end if;
  if lower(p_vote) not in ('yes','no') then raise exception 'Vote must be yes or no'; end if;
  select status into st from public.rule_proposals where id=p_proposal_id;
  if st is null then raise exception 'Proposal not found'; end if;
  if st <> 'open' then raise exception 'Voting is closed'; end if;
  insert into public.rule_proposal_votes(proposal_id,member_id,vote,updated_at)
  values(p_proposal_id,mid,lower(p_vote),now())
  on conflict(proposal_id,member_id) do update set vote=excluded.vote,updated_at=now();
end; $$;

grant execute on function public.proposal_vote(bigint,text) to anon,authenticated;

create or replace function public.proposal_clear_vote(p_proposal_id bigint)
returns void language plpgsql security definer set search_path=public as $$
declare mid bigint:=public.proposal_current_member_id();
begin
  if mid is null then raise exception 'Select your DFL member first'; end if;
  delete from public.rule_proposal_votes where proposal_id=p_proposal_id and member_id=mid;
end; $$;

grant execute on function public.proposal_clear_vote(bigint) to anon,authenticated;

create or replace function public.proposal_set_status(p_proposal_id bigint,p_status text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Commissioner access required'; end if;
  if p_status not in ('open','passed','rejected','adopted','withdrawn') then raise exception 'Invalid proposal status'; end if;
  update public.rule_proposals set status=p_status,updated_at=now() where id=p_proposal_id;
  if not found then raise exception 'Proposal not found'; end if;
end; $$;

grant execute on function public.proposal_set_status(bigint,text) to anon,authenticated;

create or replace function public.proposal_delete(p_proposal_id bigint)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Commissioner access required'; end if;
  delete from public.rule_proposals where id=p_proposal_id;
end; $$;

grant execute on function public.proposal_delete(bigint) to anon,authenticated;
