-- =====================================================================
-- DFL HQ - immutable DFLyzer receipts for completed Sleeper trades
-- Run after sleeper_schema.sql, commissioner_roles_schema.sql and
-- notifications_schema.sql. Safe to re-run.
-- =====================================================================

create table if not exists public.trade_alerts (
  id bigint generated by default as identity primary key,
  sleeper_transaction_id text not null unique
    references public.sleeper_transactions(sleeper_transaction_id) on delete restrict,
  season integer not null,
  week integer,
  occurred_at timestamptz,
  analysis_status text not null check (analysis_status in ('graded','partial','review')),
  model_version text not null,
  teams jsonb not null default '[]'::jsonb check (jsonb_typeof(teams) = 'array'),
  packages jsonb not null default '[]'::jsonb check (jsonb_typeof(packages) = 'array'),
  result jsonb,
  verdict jsonb,
  reasons jsonb not null default '[]'::jsonb check (jsonb_typeof(reasons) = 'array'),
  limitations jsonb not null default '[]'::jsonb check (jsonb_typeof(limitations) = 'array'),
  pre_trade_rosters jsonb not null default '[]'::jsonb check (jsonb_typeof(pre_trade_rosters) = 'array'),
  notification_message_id bigint unique references public.notification_messages(id) on delete set null,
  notified_at timestamptz,
  breaking_active boolean not null default true,
  breaking_started_at timestamptz not null default now(),
  breaking_ended_at timestamptz,
  breaking_ended_by bigint references public.members(id) on delete set null,
  headline_override text,
  created_at timestamptz not null default now()
);

/* Existing installations can safely re-run this file. These columns turn a
   short-lived Home slide into commissioner-controlled breaking coverage. */
alter table public.trade_alerts add column if not exists breaking_active boolean not null default true;
alter table public.trade_alerts add column if not exists breaking_started_at timestamptz not null default now();
alter table public.trade_alerts add column if not exists breaking_ended_at timestamptz;
alter table public.trade_alerts add column if not exists breaking_ended_by bigint references public.members(id) on delete set null;
alter table public.trade_alerts add column if not exists headline_override text;
/* Rows created before breaking coverage existed are receipts, not active
   emergencies. Only a genuinely recent legacy trade may launch the banner. */
update public.trade_alerts
   set breaking_active = false,
       breaking_ended_at = coalesce(breaking_ended_at, now())
 where breaking_active
   and coalesce(occurred_at, created_at) < now() - interval '72 hours';

create index if not exists trade_alerts_recent_idx
  on public.trade_alerts(occurred_at desc nulls last, created_at desc);
create index if not exists trade_alerts_season_week_idx
  on public.trade_alerts(season desc, week desc);
create index if not exists trade_alerts_breaking_idx
  on public.trade_alerts(breaking_active, occurred_at desc nulls last)
  where breaking_active;

/* A source key makes push delivery idempotent too. If a browser loses the
   response after the server inserts the inbox message, the next sync finds
   the same message instead of sending the league a second alert. */
alter table public.notification_messages add column if not exists source_key text;
create unique index if not exists notification_messages_source_key_idx
  on public.notification_messages(source_key) where source_key is not null;

alter table public.trade_alerts enable row level security;
revoke all on table public.trade_alerts from anon, authenticated;
grant select, insert on table public.trade_alerts to anon, authenticated;
grant update(notification_message_id, notified_at, breaking_active, breaking_ended_at, breaking_ended_by, headline_override)
  on table public.trade_alerts to anon, authenticated;
grant usage, select on sequence public.trade_alerts_id_seq to anon, authenticated;

drop policy if exists "public read" on public.trade_alerts;
create policy "public read" on public.trade_alerts for select
  to anon, authenticated using (true);

drop policy if exists "commissioner write" on public.trade_alerts;
create policy "commissioner write" on public.trade_alerts for insert
  to anon, authenticated
  with check (public.has_commissioner_permission('sleeper'));

/* App code only fills delivery linkage after insertion. The model receipt is
   never updated, so its grades remain the exact v1 opinion made at sync time.
   The WITH CHECK repeats authorization and prevents a public client from
   turning SELECT access into an update. */
drop policy if exists "commissioner notification link" on public.trade_alerts;
create policy "commissioner notification link" on public.trade_alerts for update
  to anon, authenticated
  using (public.has_commissioner_permission('sleeper'))
  with check (public.has_commissioner_permission('sleeper'));

comment on column public.trade_alerts.model_version is
  'Immutable analytics model identifier. Existing receipts are never regraded.';
comment on column public.trade_alerts.analysis_status is
  'graded = two-team player-only verdict; partial/review deliberately declares no winner.';

create or replace function public.keep_trade_alert_receipt_immutable()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if row(new.sleeper_transaction_id, new.season, new.week, new.occurred_at,
         new.analysis_status, new.model_version, new.teams, new.packages,
         new.result, new.verdict, new.reasons, new.limitations,
         new.pre_trade_rosters, new.created_at)
     is distinct from
     row(old.sleeper_transaction_id, old.season, old.week, old.occurred_at,
         old.analysis_status, old.model_version, old.teams, old.packages,
         old.result, old.verdict, old.reasons, old.limitations,
         old.pre_trade_rosters, old.created_at)
  then
    raise exception 'Trade alert model receipts are immutable';
  end if;
  return new;
end;
$$;

drop trigger if exists trade_alert_receipt_immutable on public.trade_alerts;
create trigger trade_alert_receipt_immutable
before update on public.trade_alerts
for each row execute function public.keep_trade_alert_receipt_immutable();

revoke all on function public.keep_trade_alert_receipt_immutable() from public;

/* The receipt stays immutable; this RPC only changes the live presentation
   state. Authorization is resolved from the existing commissioner session,
   never from a caller-supplied member id. */
create or replace function public.end_trade_breaking_coverage(alert_id bigint)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare affected integer;
begin
  if not public.has_commissioner_permission('sleeper') then
    raise exception 'Commissioner Sleeper permission required';
  end if;
  update public.trade_alerts
     set breaking_active = false,
         breaking_ended_at = now(),
         breaking_ended_by = nullif(
           nullif(current_setting('request.headers', true), '')::json ->> 'x-member-id', ''
         )::bigint
   where id = alert_id and breaking_active;
  get diagnostics affected = row_count;
  return affected > 0;
end;
$$;

revoke all on function public.end_trade_breaking_coverage(bigint) from public;
grant execute on function public.end_trade_breaking_coverage(bigint) to anon, authenticated;
