// =====================================================================
// DFL Sportsbook - fake SIN, real DFL consequences.
// =====================================================================
import { db, hasPermission } from "../supabase.js";
import { currentMember } from "../members.js";
import { esc, toast } from "../ui.js";

const fmtOdds=n=>Number(n)>0?`+${Number(n)}`:String(Number(n));
const fmtTime=v=>v?new Date(v).toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"";
const isOpen=m=>m.status==="open"&&(!m.closes_at||new Date(m.closes_at)>new Date());
const isGolf=m=>m.category==="Golf"&&String(m.auto_key||"").startsWith("golf:");

export async function render(view){
 const me=currentMember();
 if(!me){view.innerHTML=`<h1>DFL Sportsbook</h1><div class="card"><div class="card-body">Pick your league member first. The house needs to know whose SIN it is taking.</div></div>`;return;}
 view.innerHTML=`<h1>DFL Sportsbook</h1><div class="card"><div class="card-body muted">Opening the book…</div></div>`;
 let wallet,ledger,leaders,markets,outcomes,bets,autoState=null;let autoReady=true,golfReady=true;
 try{
  const touch=await db().rpc("sportsbook_touch_wallet");if(touch.error)throw touch.error;wallet=touch.data?.[0]||null;
  try{const g=await db().rpc("sportsbook_maintain_golf_board");if(g.error)throw g.error;}catch{golfReady=false;}
  try{const a=await db().rpc("sportsbook_maintain_auto_board",{target_open:6});if(a.error)throw a.error;autoState=a.data?.[0]||null;}catch{autoReady=false;}
  const [lr,br,mr,or,btr]=await Promise.all([db().rpc("sportsbook_my_ledger",{row_limit:16}),db().rpc("sportsbook_leaderboard"),db().from("sportsbook_markets").select("*").order("created_at",{ascending:false}).limit(100),db().from("sportsbook_outcomes").select("*").order("sort_order"),db().rpc("sportsbook_my_bets",{row_limit:30})]);
  const err=lr.error||br.error||mr.error||or.error||btr.error;if(err)throw err;ledger=lr.data||[];leaders=br.data||[];markets=mr.data||[];outcomes=or.data||[];bets=btr.data||[];
 }catch(err){view.innerHTML=`<h1>DFL Sportsbook</h1><div class="card note"><div class="card-body">The Sportsbook needs <strong>sportsbook_schema.sql</strong> in Supabase.<br><span class="muted tiny">${esc(err.message||String(err))}</span></div></div>`;return;}
 const byMarket=new Map();for(const o of outcomes){const k=String(o.market_id);if(!byMarket.has(k))byMarket.set(k,[]);byMarket.get(k).push(o);}
 const marketMap=new Map(markets.map(m=>[String(m.id),m])),outcomeMap=new Map(outcomes.map(o=>[String(o.id),o]));
 const open=markets.filter(isOpen),golf=open.filter(isGolf),other=open.filter(m=>!isGolf(m)),rulings=markets.filter(m=>m.status==="locked"),canBook=hasPermission("sportsbook");
 view.innerHTML=`<div id="sportsbook-wrap">
 <header class="page-head"><div><h1>DFL Sportsbook</h1><p class="muted">Fake money. Real receipts. The house has no respect for your feelings.</p></div></header>
 <section class="card"><div class="card-title-row"><div><div class="card-title">Your bankroll</div><p class="muted tiny">${esc(me.display_name)} · 500 starting SIN · +50 every 24 hours</p></div><strong style="font-size:28px;font-variant-numeric:tabular-nums">${Number(wallet?.balance||0).toLocaleString()} SIN</strong></div><div class="row" style="margin-top:10px">${Number(wallet?.credited||0)>0?`<span class="pill green">+${wallet.credited} daily SIN</span>`:""}<span class="pill">Next drip ${esc(fmtTime(wallet?.next_daily_at))}</span>${golf.length?`<span class="pill green">Golf book · ${golf.length} lines</span>`:autoReady?`<span class="pill green">Lore board · ${Number(autoState?.open_auto??open.length)} live</span>`:""}</div></section>
 ${!golfReady?`<div class="card note"><div class="card-body"><strong>The golf book is still in the parking lot.</strong><br><span class="muted">Run <strong>sportsbook_golf_schema.sql</strong> in Supabase. It replaces the soft auto props with real outing/team/match lines and a much meaner fallback board.</span></div></div>`:""}
 ${canBook&&rulings.length?rulingQueue(rulings,byMarket):""}${canBook?commissionerBook():""}
 ${golf.length?`<section class="block"><h2 class="section-title">Golf main event<span class="count">${golf.length}</span></h2><div class="card note"><div class="card-body"><strong>League Lore found an actual event to gamble on.</strong><br><span class="muted">These lines are built from the teams and matches already in DFL Golf. Neutral odds stay neutral until the league has enough real player history to justify handicaps. Lore can be an asshole; it cannot make up stats.</span></div></div>${golf.map(m=>marketCard(m,byMarket.get(String(m.id))||[],bets,canBook)).join("")}</section>`:""}
 <section class="block"><h2 class="section-title">${golf.length?"Degenerate board":"The board"}<span class="count">${other.length}</span></h2>${other.length?other.map(m=>marketCard(m,byMarket.get(String(m.id))||[],bets,canBook)).join(""):`<div class="card"><div class="card-body"><strong>The windows are dark.</strong><br><span class="muted">Nobody has given the house anything stupid enough to price yet.</span></div></div>`}</section>
 ${bets.length?`<section class="block"><h2 class="section-title">Your tickets</h2>${bets.slice(0,10).map(b=>ticketCard(b,marketMap,outcomeMap)).join("")}</section>`:""}
 <section class="block"><h2 class="section-title">SIN leaderboard</h2><div class="card"><div class="card-body">${leaders.length?leaders.slice(0,12).map((r,i)=>`<div class="row" style="justify-content:space-between;padding:6px 0"><span><strong>${i+1}.</strong> ${esc(r.display_name)}</span><strong>${Number(r.balance).toLocaleString()} SIN</strong></div>`).join(""):`<span class="muted">The first bankroll has not been opened yet.</span>`}</div></div></section>
 <section class="block"><h2 class="section-title">Receipts</h2><div class="card"><div class="card-body">${ledger.length?ledger.map(r=>`<div class="row" style="justify-content:space-between;padding:6px 0"><span><strong>${esc(r.note||r.kind)}</strong><br><span class="muted tiny">${esc(fmtTime(r.created_at))}</span></span><strong>${r.amount>0?"+":""}${r.amount} SIN</strong></div>`).join(""):`<span class="muted">No SIN has moved yet.</span>`}</div></div></section><p class="muted tiny" style="text-align:center">SIN is DFL play money only. No cash value. The house remembers everything.</p></div>`;
 wireBets(view,outcomeMap);if(canBook)wireCommissioner(view);
}
function rulingQueue(markets,byMarket){return `<section class="block"><h2 class="section-title">Needs a ruling<span class="count">${markets.length}</span></h2><div class="card note"><div class="card-body muted">Reality happened outside the app. Pick what actually happened, or void it and every open ticket gets its SIN back.</div></div>${markets.map(m=>{const os=byMarket.get(String(m.id))||[];return `<article class="card"><span class="muted tiny">${esc(String(m.category||"DFL").toUpperCase())} · HOUSE RULING</span><h3 class="card-heading">${esc(m.title)}</h3><div class="row" style="gap:8px;flex-wrap:wrap">${os.map(o=>`<button type="button" class="btn small" data-settle-market="${m.id}" data-settle-outcome="${o.id}">${esc(o.label)} won</button>`).join("")}</div><div class="card-meta"><button type="button" class="linkbtn" data-void-market="${m.id}">Void + refund</button></div></article>`}).join("")}</section>`;}
function commissionerBook(){return `<section class="block"><h2 class="section-title">The window</h2><form class="card" id="sportsbook-market-form"><div class="card-title">Post a Commissioner Special</div><p class="muted tiny">The automatic book handles real DFL Golf when it can. This window is for whatever fresh bullshit deserves a price.</p><label for="book-title">Market</label><input id="book-title" maxlength="120" required placeholder="Put somebody's dignity on the board."><label for="book-category">Category</label><select id="book-category"><option>DFL Life</option><option>Fantasy</option><option>Golf</option><option>Marvel</option><option>Gaming</option></select><label for="book-close">Closes</label><input id="book-close" type="datetime-local"><label for="book-note">House note</label><input id="book-note" maxlength="180" placeholder="Make it hurt."><div class="section-head"><h3>Lines</h3></div>${outcomeInput(1,"YES","-110")}${outcomeInput(2,"NO","-110")}${outcomeInput(3,"","")}<div class="row-end"><button class="btn" type="submit">Open the window</button></div></form></section>`;}
function outcomeInput(n,label,odds){return `<div class="row" style="gap:8px"><input data-book-label="${n}" maxlength="60" placeholder="Outcome ${n}" value="${esc(label)}" ${n<3?"required":""}><input data-book-odds="${n}" inputmode="numeric" placeholder="-110" value="${esc(odds)}" style="max-width:100px" ${n<3?"required":""}></div>`;}
function marketCard(m,outcomes,bets,canBook){const mine=new Set((bets||[]).filter(b=>String(b.market_id)===String(m.id)&&b.status==="open").map(b=>String(b.outcome_id)));const source=isGolf(m)?"LEAGUE LORE · GOLF BOOK":m.auto_key?"LEAGUE LORE · DISRESPECT DESK":m.source==="lore"?"LEAGUE LORE":"COMMISSIONER SPECIAL";return `<article class="card"><div class="card-title-row"><div><span class="muted tiny">${esc(String(m.category||"DFL").toUpperCase())} · ${source}</span><h3 class="card-heading" style="margin-top:3px">${esc(m.title)}</h3></div>${m.closes_at?`<span class="pill">Closes ${esc(fmtTime(m.closes_at))}</span>`:""}</div>${m.lore_note?`<p class="muted">${esc(m.lore_note)}</p>`:""}<div style="display:grid;gap:8px;margin-top:10px">${outcomes.map(o=>`<button class="btn ghost" data-bet-outcome="${o.id}" style="display:flex;justify-content:space-between;align-items:center"><span>${esc(o.label)}${mine.has(String(o.id))?` <small>· ticket open</small>`:""}</span><strong>${fmtOdds(o.odds_american)}</strong></button>`).join("")}</div>${canBook?`<div class="card-meta">House controls: ${outcomes.map(o=>`<button type="button" class="linkbtn" data-settle-market="${m.id}" data-settle-outcome="${o.id}">${esc(o.label)}</button>`).join(" · ")} · <button type="button" class="linkbtn" data-void-market="${m.id}">Void</button></div>`:""}</article>`;}
function ticketCard(b,mm,om){const m=mm.get(String(b.market_id)),o=om.get(String(b.outcome_id));return `<div class="card"><div class="card-title-row"><div><strong>${esc(o?.label||"Ticket")}</strong><div class="muted tiny">${esc(m?.title||"DFL Sportsbook")} · ${fmtOdds(b.odds_american)}</div></div><span class="pill ${b.status==="won"?"green":b.status==="lost"?"grey":b.status==="void"?"warn":""}">${esc(b.status)}</span></div><div class="card-meta">${b.stake} SIN risked · ${b.potential_payout} SIN return</div></div>`;}
function wireBets(view,outcomeMap){view.querySelectorAll("[data-bet-outcome]").forEach(btn=>btn.addEventListener("click",async()=>{const o=outcomeMap.get(String(btn.dataset.betOutcome));if(!o)return;const raw=prompt(`How much SIN on ${o.label} (${fmtOdds(o.odds_american)})?`,"50");if(raw==null)return;const stake=Number(String(raw).replace(/\D/g,""));if(!Number.isInteger(stake)||stake<1){toast("Enter a valid SIN stake",true);return;}btn.disabled=true;try{const{error}=await db().rpc("sportsbook_place_bet",{target_outcome_id:Number(o.id),sin_stake:stake});if(error)throw error;toast("Ticket punched");render(view);}catch(err){toast(err.message||"The house rejected that ticket",true);btn.disabled=false;}}));}
function wireCommissioner(view){const form=view.querySelector("#sportsbook-market-form");form?.addEventListener("submit",async e=>{e.preventDefault();const os=[1,2,3].map(n=>({label:form.querySelector(`[data-book-label="${n}"]`)?.value.trim()||"",odds:Number(form.querySelector(`[data-book-odds="${n}"]`)?.value.trim()||0)})).filter(o=>o.label);if(os.length<2||os.some(o=>!(o.odds<=-100||o.odds>=100))){toast("Use at least two outcomes with American odds like -110 or +150",true);return;}const closes=form.querySelector("#book-close").value,btn=form.querySelector('button[type="submit"]');btn.disabled=true;try{const{error}=await db().rpc("sportsbook_create_market",{market_title:form.querySelector("#book-title").value.trim(),market_category:form.querySelector("#book-category").value,market_source:"commissioner",market_closes_at:closes?new Date(closes).toISOString():null,market_lore_note:form.querySelector("#book-note").value.trim(),market_outcomes:os});if(error)throw error;toast("The window is open");render(view);}catch(err){toast(err.message||"Could not open that market",true);btn.disabled=false;}});view.querySelectorAll("[data-settle-market]").forEach(btn=>btn.addEventListener("click",async()=>{const label=btn.textContent.replace(/ won$/i,"").trim();if(!confirm(`Settle this market with ${label} as the winner? This pays every winning ticket.`))return;btn.disabled=true;try{const{error}=await db().rpc("sportsbook_settle_market",{target_market_id:Number(btn.dataset.settleMarket),winning_outcome_id:Number(btn.dataset.settleOutcome)});if(error)throw error;toast("Market settled. The house has spoken.");render(view);}catch(err){toast(err.message||"Could not settle that market",true);btn.disabled=false;}}));view.querySelectorAll("[data-void-market]").forEach(btn=>btn.addEventListener("click",async()=>{if(!confirm("Void this market and refund every open ticket?"))return;btn.disabled=true;try{const{error}=await db().rpc("sportsbook_void_market",{target_market_id:Number(btn.dataset.voidMarket)});if(error)throw error;toast("Market voided. SIN refunded.");render(view);}catch(err){toast(err.message||"Could not void that market",true);btn.disabled=false;}}));}
